
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
<<<<<<< HEAD
// Tue Jun 09 14:05:42 CEST 2015
=======
// Tue Jun 09 14:29:44 CEST 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int SIN = 12;
  public static final int PLUS = 3;
  public static final int CTG = 15;
  public static final int RPARENT = 10;
  public static final int COS = 13;
  public static final int POW = 7;
  public static final int ID = 17;
  public static final int NEW_LINE = 2;
  public static final int LPARENT = 9;
  public static final int EOF = 0;
  public static final int NUMBER = 16;
  public static final int DIVIDE = 6;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int EQ = 8;
  public static final int TAN = 14;
  public static final int UMINUS = 11;
}

