
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 19 22:59:27 CEST 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RPARENT = 9;
  public static final int MINUS = 4;
  public static final int DIVIDE = 6;
  public static final int POW = 7;
  public static final int CTG = 13;
  public static final int TAN = 12;
  public static final int SIN = 10;
  public static final int NUMBER = 14;
  public static final int COS = 11;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int error = 1;
  public static final int TIMES = 5;
  public static final int NEW_LINE = 2;
  public static final int LPARENT = 8;
}

